### ISSUE TITLE
Using CI and qcsubmit to validate submissions

### ISSUE THREAD

**Issue by jthorton** [openforcefield/qca-dataset-submission#108]
I would like to propose that we use QCSubmit's built-in validators to make sure the submission JSON is valid and have this run through CI as a test before we submit the dataset to the archive. Here we don't have to force people to use QCSubmit to generate their data if they do not want to but we can specify that the JSON follows a certain schema which is defined in QCSubmit making it easy to validate.

__PLAN__
-  the user uploads the usual information about generating the dataset 
- the dataset should be in a file called dataset.json which follows the qcsubmit schema
- the CI will then use the validators in QCSubmit to check the dataset for:
   - connected proper/improper torsions
   - linear torsions that have been highlighted by mistake
   -  basis set coverage of the dataset
   -  complete dataset metadata

If all of the stages are green then we can submit the dataset with confidence.

Are there any other checks which we should perform?

**Comment by dotsdl** [comment]
Thank you for putting this proposal together @jthorton! This would be a huge advancement in our dataset submission process!

**Comment by davidlmobley** [comment]
There was sort of a related issue that came up in Slack. Maybe we should do some quick chemistry sanity checks (does valence appear complete, for example) at the same time? (Though I'm not sure if that's something that'd be in QCSubmit already, so if not, that'd be a sensible enhancement for later.)

Um, also -- should we check connectivity? (What if someone tried to submit a molecule which was really two disconnected units?)

**Comment by jthorton** [comment]
Would we just want an incomplete valence warning to pop up for each molecule? 
Good point about the connectivity Ill make sure to check for this as well.

**Comment by jthorton** [comment]
The first pass at the types of validation that will run on submissions can be found [here]( https://github.com/openforcefield/qca-dataset-submission/pull/106#issuecomment-658809335). I will be adding constraint checks soon, other than that is there anything else that would be helpful in the report?

**Comment by dotsdl** [comment]
Awesome work @jthorton! I'll solicit for comments in Slack. You've built a powerful framework for this here!

**Comment by dotsdl** [comment]
I think this one is satisfied by the merge of #106. @JoshHorton did we want to keep this open or close it?

**Comment by j-wags** [comment]
I'm assuming this is done, but feel free to reopen if not!
