### ISSUE TITLE
Potential dataset: VEHICLe

### ISSUE THREAD

**Issue by j-wags** [openforcefield/qca-dataset-submission#11]
(Edited by @jchodera):

To ensure good scaffold coverage, it was suggested we include the [VEHICLe dataset](ftp://ftp.ebi.ac.uk/pub/databases/chembl/VEHICLe/) (Virtual Exploratory heterocyclic library) from [Heteroaromatic rings of the future](http://doi.org/10.1021/jm801513z). This dataset contains ~25K heteroaromatic ring systems, some of which existing current drugs, and many of which are likely synthesizable.

For future reference, the compressed dataset is here: [VEHICLe.csv.gz](https://github.com/openforcefield/qca-dataset-submission/files/3351946/VEHICLe.csv.gz)

Reference:

William R. Pitt, David M. Parry, Benjamin G. Perry, and Colin R. Groom.
Heteroaromatic rings of the future.
J Med Chem 52:2952, 2009.
[[DOI]](http://doi.org/10.1021/jm801513z) [[FTP]](http://ftp.ebi.ac.uk/pub/databases/chembl/VEHICLe/) [[PDF]](https://github.com/openforcefield/qca-dataset-submission/files/3351948/jm801513z.pdf)

**Comment by jchodera** [comment]
I'm working on constructing this dataset right now.

**Comment by dgasmith** [comment]
This dataset is currently being computed 10k/25k tasks complete.

**Comment by dgasmith** [comment]
This set is largely computed. Closing.
