### ISSUE TITLE
Handling Multiple QC specifications

### ISSUE THREAD

**Issue by jthorton** [openforcefield/qca-dataset-submission#123]
A recent [PR](https://github.com/openforcefield/qca-dataset-submission/pull/121) added our first dataset with multiple QC specs which seemed to work however this created a new dataset in the archive for each spec rather than one collection with each spec stored in the object map. QCSubmit now has the ability to store multiple QCSpecs in the datasets and factories and will start new compute for all specs automatically under one dataset but we need to update the validate CI to capture and display this info in the PR. 

I will also add a new part of the validate CI which is specifically for adding extra QCSpecifications for current datasets which will perform the normal validation but on the dataset already in QCArchive aginst the new method and basis combination.

To do this the submitter can just add a QCSubmit dataset.json with no molecules defined instead only the dataset_name and qcspec need to be filled in, where the name is the name in the Archive. The CI can then access the collection and validate the spec against the molecules before allowing QCSubmit to add the extra compute.

**Comment by dotsdl** [comment]
Thank for identifying this @jthorton! This will definitely be useful for the usage pattern we are seeing in #121 and #120, which may be pretty common going forward.

**Comment by dotsdl** [comment]
I think we've solved this. Closing! Re-open if I'm mistaken.
