### ISSUE TITLE
Use Github Pages for updating dashboard?

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/qca-dataset-submission#163]
We could use [Github Pages](https://pages.github.com/) for this repository as a reporting mechanism for throughput (optimizations completed, which compute resource, etc.). This could get updated at some frequency (daily, twice-weekly, weekly, etc.) as a Github Action.

**Comment by j-wags** [comment]
Closing since I think this was resolved/is no longer relevant. Feel free to reopenif I'm wrong!
