### ISSUE TITLE
Deduplication for [OpenFF Optimizaiton Set 1] and Hessian Submission

### ISSUE THREAD

**Issue by yudongqiu** [openforcefield/qca-dataset-submission#24]
Now the error jobs are all fixed in [OpenFF Optimizaiton Set 1] #6 , the next step is to aggregate and deduplicate the optimized geometries, then submit one hessian calculation for each unique optimized geometry.

For the geometry aggregation and deduplication, it will be nice if the feature is provided through a function like `OptimizationDataset.get_final_molecules(deduplicate=True)`. An issue was created for this feature:  https://github.com/MolSSI/QCFractal/issues/299

After the deduplication, we will likely add one more step to check if the topology has changed. If so we may want to skip the result for now.

Then we need to submit Hessian calculation for each of the final unique optimized geometry. We might wang to compute Wiberg bond orders in these jobs. These "single point" calculations may be put into a "ReactionDataset", or we can create a special "HessianDataset".

**Comment by yudongqiu** [comment]
The deduplication will likely play a small role in this particular OptimizationDataset because we only generated in average 2 conformers per molecules. In other datasets it will play a more significant role in reducing the total cost.

**Comment by dgasmith** [comment]
Considering the size of this dataset is 1/25th the size of VEHICLe should we go ahead and run all Hessians in this case?

**Comment by yudongqiu** [comment]
Sure I agree we can just run all the Hessians for this dataset. Do we submit the hessians as a separate dataset?
