### ISSUE TITLE
Switch Docker image push to use GHCR, deprecate DockerHub

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/qca-dataset-submission#328]
Since GHCR is now a fairly mature option for Docker image hosting (we've been using this for [alchemiscale](https://github.com/openforcefield/alchemiscale), we should try switching over to this from DockerHub. This will simplify management of images, keeping them alongside the repo itself, and avoid potential fees from DockerHub (though with our open source status, we have so far avoided these).

**Comment by j-wags** [comment]
The dockerhub renewal process was extremely easy and took less than 30 minutes of my time this year. So we can keep this open but I don't see an urgent need to action it.
