### ISSUE TITLE
Update `validation.py` and `lifecycle.py` automation for compatibility with `openff-qcsubmit` 0.50.0

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/qca-dataset-submission#329]
Now that [openff-qcsubmit 0.50.0](https://github.com/openforcefield/openff-qcsubmit/releases/tag/0.50.0) is out, giving compatibility with [QCFractal 0.51](https://github.com/MolSSI/QCFractal/releases/tag/v0.51), we want to update the Github Actions automation on this repo found in:
- [x] #330
- [x] #331

And the utilities defined in:
- [x] #332

We will keep the existing lifecycle model defined in the [README](https://github.com/openforcefield/qca-dataset-submission/blob/master/README.md) for now, although it may warrant revisiting due to advancements in QCFractal itself, such as some form of in-server error cycling.

**Comment by j-wags** [comment]
As best as I know, these have largely been handled by a combination of https://github.com/openforcefield/qca-dataset-submission/pull/336 and https://github.com/openforcefield/openff-qcsubmit/pull/195
