### ISSUE TITLE
submit hessian jobs for the coverage set of molecules

### ISSUE THREAD

**Issue by yudongqiu** [openforcefield/qca-dataset-submission#33]
The optimizations for the coverage set of molecules were submitted in
https://github.com/openforcefield/qca-dataset-submission/tree/master/2019-06-25-smirnoff99Frost-coverage

We want to submit hessian calculation for the optimized geometries. 
The simplest way is to submit one hessian computation for each optimization record. The downside is that it is possible there are duplications in the optimized geometries, and we will most likely not use all of the data in fitting.

Since we are more interested in the hessian of the global minimum of each molecule, we can pick the lowest energy structure for each molecule out of the optimized geometries, and just submit hessian jobs for those. This will greatly reduce the total cost of this dataset.

**Comment by dgasmith** [comment]
If you only want the minimum of the previous dataset, that is something that you will need to code up as there are plenty of choices involved. I believe I provided a template to do this using the `Molecule.align` functionality that we have built in.

Do you want me to submit the full dataset as there are only 156 Hessians, for comparison we have computed ~22k so far?

Are these high or normal priority compared to the current Boron queue.

**Comment by yudongqiu** [comment]
The coverage set have about 1k optimization records, may I ask why there is only 156 hessians?

I agree we can submit the full dataset if it doesn't take too much time. The code is not complicated but I just have too many things on my hand at this moment.

In the last meeting we agreed that these hessian jobs should be put in front the Boron queue.

Thanks!

**Comment by dgasmith** [comment]
Hessians are largely complete.
