### ISSUE TITLE
Rename dataset 

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/qca-dataset-submission#39]
The Torsion dataset in pr #34 needs to be renamed to `Substituted phenyl set`. 

In addition, it seems like only the [`phenyl JSON file`](https://github.com/openforcefield/qca-dataset-submission/blob/master/2019-07-25-phenyl-set/phenyl_set_input.tar.jz) was submitted and not the [`biphenyl JSON file`](https://github.com/openforcefield/qca-dataset-submission/blob/master/2019-07-25-phenyl-set/biphenyls_set_input.tar.gz)

**Comment by dgasmith** [comment]
Ok, I can rename. Would you like `biphenyl` added to the dataset?

**Comment by dgasmith** [comment]
Looks like the README commented on the `phenyl_set_inputs.json` input. It is always good to be *very* explicit in what we want added.

**Comment by ChayaSt** [comment]
> Ok, I can rename. Would you like biphenyl added to the dataset?

Yes.
 >Looks like the README commented on the phenyl_set_inputs.json input. It is always good to be very explicit in what we want added.

There is also a comment on the `biphenyl_set_inputs.json` in the README but I see it's not explicit enough.  I can update the README so it is very explicit that both of these JSON files need to go into this set.

**Comment by dgasmith** [comment]
This was completed some time ago.
