### ISSUE TITLE
Directory naming conventions

### ISSUE THREAD

**Issue by jchodera** [openforcefield/qca-dataset-submission#52]
The directory naming conventions in this repo are all over the place. We have different date formats (the correct ISO8601 date format `2019-07-25` and the incorrect format `06-28-19`) along with both names that use spaces and `hyphenate-everything`.

I propose we standardize on
* [ISO 8601 dates](https://xkcd.com/1179/) (e.g. `2019-07-25`)
* Using spaces, which are supported by all modern filesystems

**Comment by jchodera** [comment]
cc: #15

**Comment by davidlmobley** [comment]
I'd still tend to prefer underscores, as tools unpredictably choke on spaces -- e.g. PyMol does not behave well with them, as well as various other tools. But +1 to ISO dates.

**Comment by jchodera** [comment]
For now, we're standardizing on dashes (`-`) instead of spaces (` `).
