### ISSUE TITLE
Add default level of theory to kinase inhibitor set

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/qca-dataset-submission#72]
The current Kinase inhibitors WBO distributions `OptimizationDataset` [`02_create_optimization_input.py`](https://github.com/openforcefield/qca-dataset-submission/blob/master/2019-11-27-kinase-inhibitor-optimization/02_create_optimization_input.py) only specifies hf3c level of theory. I want to add the OFF default level of theory to this dataset. 

ETA: Also compute WBO at default level.

**Comment by ChayaSt** [comment]
[Here](https://github.com/choderalab/fragmenter_data/blob/figure-1/manuscript-figures/figure-4/data_generation/indices_to_comput.json) are the indices of the smaller molecules (less than 30 heavy atoms) to optimize at a higher level of theory. I also added two larger molecules (31 and 37 heavy atoms) that we need to optimize at the more expensive level of theory.

**Comment by dgasmith** [comment]
I have submitted these while I fix the HF-3c bug.
