### ISSUE TITLE
Torsiondrive scans for the coverage set

### ISSUE THREAD

**Issue by yudongqiu** [openforcefield/qca-dataset-submission#8]
For the "coverage set" molecules, we want to both run geometry optimizations and torsiondrive scans.

The geometry optimizations are submitted in the folder `qca-dataset-submission/6-25-19-smirnoff99Frost-coverage/`.

A few questions related:
1. Is it a good idea to create a new folder for submitting the torsiondrive jobs?
2. If so, I will copy the `generate.py` @ChayaSt wrote, and add a few other scripts for selecting the dihedrals, and write another `create_dataset.py` that finally creates the TorsiondriveDataset. Does that sound like a good plan?
3. Do we want to scan all possible dihedrals for all molecules in this set, or do we want to filter that and scan a subset? What kind of filter do we want to apply?

Some of the questions may not have a clear answer yet. I think this issue might be a good place for discussion.

**Comment by davidlmobley** [comment]
We don't need to scan all dihedrals (most we'll likely have coverage of), but we certainly need to scan all dihedrals that only occur in one molecule. Maybe you could check which SMIRKS patterns we've not already scanned, and scan those here?

**Comment by yudongqiu** [comment]
@davidlmobley Sure. I can try to implement a filter that keeps only the first dihedral that matches each SMIRKS patten. Does that sound good?

**Comment by davidlmobley** [comment]
It'd be good to have "a few" occurrences of each if we can afford it, because that would allow us to check if the chemical perception is right at a later date. But... if it's not affordable then the first instance of each is fine.

**Comment by yudongqiu** [comment]
Sure I can try to keep 2-3 if it's affordable (total number of scans < 2000).
Although the Roche set covers 131/258 of the torsion k parameters, I would try to keep the generation of this dataset independent of that one, so it's easier to reproduce and gives better insights in analysis.

**Comment by davidlmobley** [comment]
Sounds great, @yudongqiu .

**Comment by yudongqiu** [comment]
This is submitted in #26 
I eventually chose a max number of 5 torsions per SMIRKs.
One thing to note here is that this submission method selects the torsion based on the force field.

This means when new torsion terms are added to the force field, the existing dataset will not have torsion scans for that new term. Therefore the submission may need to be re-performed when we need those new torsion terms being scanned here.
