### ISSUE TITLE
Hide TorsionDriveDataset that does not use OFF default level of theory

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/qca-dataset-submission#80]
The OpenFF Fragmenter Phenyl Benchmark dataset does not use the OFF default level of theory so it is not used in analysis for the paper. It is cluttering up the list of `TorsionDriveDataset` so it might be good to hide it. 

I just want to make sure before it is hidden that it will still be accessible, just not in printed in the list.

**Comment by dgasmith** [comment]
This is now hidden a direct query or `client.list_collections("TorsionDriveDataset", show_hidden=True)` will still display this.
